package Preprocessor;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;

/** Generated by ChatGPT */
public class Heatmap {
    private static final Map<Character, Color> COLOR_MAP = createColorMap();
    
    private static Map<Character, Color> createColorMap() {
        Map<Character, Color> map = new HashMap<>();
        float hueStep = 1.0f / 128.0f;
        for (int i = 0; i < 128; i++) {
            char c = (char) i;
            float hue = i * hueStep;
            Color color = Color.getHSBColor(hue, 1.0f, 1.0f);
            map.put(c, color);
        }
        return map;
    }
    
    public static Color getColorForChar(char c) {
        return COLOR_MAP.get(c);
    }
}